# Welcome to Jekyll!
# This is my webpage info.

title: Samuel G. Moreno S.
email: samuelg.morenos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website. I'm building it and hope you are patient with me. Please feel welcomed.
  I will include some interesting stuff here, like my favorite repositories, some images, some nice research material, etc.

baseurl: "Home" # the subpath of your site, e.g. /blog
url: "https://gregsom-msc.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: GregSom-MSc

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
